global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus stesso
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Fail2Ban exporter
  - job_name: 'fail2ban'
    static_configs:
      - targets: ['localhost:9000']
        labels:
          instance: 'server'

  # Node exporter
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: 'server'

  # Metriche di Promtail (Locale)
  - job_name: 'promtail-metrics'
    static_configs:
      - targets: ['localhost:9080']

  # Metriche di Loki (Server Remoto/WSL)
  - job_name: 'loki-server-metrics'
    static_configs:
      - targets: ['10.99.88.237:3100']

  # Disk Space Exporter (custom metrics)
  - job_name: 'disk_exporter'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['10.99.88.114:9200']
        labels:
          instance: 'server'
          service: 'disk_monitoring'
