global:
  scrape_interval: 5s

scrape_configs:
  # Prometheus stesso
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "node_exporter"
    static_configs:
      - targets: ["10.99.88.114:9100"]

  - job_name: "promtail"
    static_configs:
      - targets: ["10.99.88.114:9080"]
  # Fail2Ban exporter
  - job_name: 'fail2ban'
    static_configs:
      - targets: ['10.99.88.114:9000']
        labels:
          instance: 'server'
  # Disk Space Exporter (custom metrics)
  - job_name: 'disk_exporter'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['10.99.88.114:9200']
        labels:
          instance: 'server'
          service: 'disk_monitoring'
  # Metriche di Loki (Server Remoto/WSL)
  - job_name: 'loki-server-metrics'
    static_configs:
      - targets: ['localhost:3100']
